model:
  name: BetaVAE
  channel_mults: [1, 2, 2, 2, 2]
  num_channels: 64
  num_groups: 16
  norm: GroupNorm
  latent_channels: 3
  dropout: 0

image:
  channels: 3
  size: 128

dataset:
  name: CelebA
  datasets_dir: datasets

training:
  num_epochs: 32
  batch_size: 32
  lr: 0.0003
  seed: 0
  num_workers: 2
  pin_memory: True
  prefetch_factor: 1
  num_samples: 100
  num_reconstructions: 100
  num_interpolations: 10
  eval_steps: 100
  checkpoints_dir: ckpts
  warmup_steps_percentage: 0.05
  # device: cuda
  # amp: True
  # dtype: bfloat16
  device: mps
  amp: False
  dtype: float32
wandb:
  project: vae
  enabled: False