model:
  name: VAE
  channel_mults: [1, 2, 2]
  num_channels: 32
  num_groups: 16
  norm: GroupNorm
  latent_dim: 128
  dropout: 0

image:
  channels: 1
  size: 28

dataset:
  name: MNIST
  datasets_dir: datasets

training:
  num_epochs: 256
  batch_size: 256
  lr: 0.0003
  seed: 0
  num_workers: 2
  pin_memory: True
  prefetch_factor: 1
  num_samples: 100
  num_reconstructions: 100
  num_interpolations: 10
  eval_steps: 100
  checkpoints_dir: ckpts
  warmup_steps_percentage: 0.05
  device: mps
  amp: False
  dtype: float32

wandb:
  project: vae
  enabled: True