model:
  name: VAE
  channel_mults: [1, 2, 2, 2]
  num_channels: 32
  num_groups: 16
  norm: GroupNorm
  latent_dim: 16
  dropout: 0

image:
  channels: 3
  size: 32

dataset:
  name: SVHN
  datasets_dir: datasets

training:
  num_epochs: 32
  batch_size: 128
  lr: 0.0003
  seed: 0
  dtype: float32
  num_workers: 0
  pin_memory: False
  prefetch_factor: 0
  num_samples: 100
  num_reconstructions: 100
  num_interpolations: 10
  eval_steps: 100
  checkpoints_dir: checkpoints
  warmup_steps_percentage: 0.05

wandb:
  project: vae
  enabled: True